### ISSUE TITLE
"invalid plugin name \"openstack\"

### ISSUE THREAD

**Issue by AlwaySummit** [Lirt/velero-plugin-for-openstack#19]
Hi @Lirt 

I notice that you merged a PR #16 for the provider name changed. However, I encounter an error due to this more likely. Do you have any idea about this? Thanks.
![image](https://user-images.githubusercontent.com/20851530/111935158-d59b0f00-8afd-11eb-8b4d-b36e9dfac2b1.png)

**Comment by AlwaySummit** [comment]
@Lirt 0.2.0 is working well but 0.2.1 has the aforementioned issue.

**Comment by Lirt** [comment]
Hi @AlwaySummit, I didn't notice it. Thank you for reporting. Can you stick to `v0.2.0` release? I will remove and re-push the tag when I figure out new provider naming. 

I want to keep it to be related to community and maybe someone in Velero will help with the proper naming (https://github.com/vmware-tanzu/velero/pull/3607)

**Comment by Lirt** [comment]
Hi @AlwaySummit 

I re-released v0.2.1 https://github.com/Lirt/velero-plugin-for-openstack/releases/tag/v0.2.1.

The change was done in https://github.com/Lirt/velero-plugin-for-openstack/pull/22 and it changes provider name to `community.openstack.org/openstack`. 

Sorry for inconvenience and thank you for your patience.
