### ISSUE TITLE
Restore partially failed due to 'failed to allocate requested HealthCheck NodePort'

### ISSUE THREAD

**Issue by AlwaySummit** [Lirt/velero-plugin-for-openstack#23]
Hi @Lirt 

I met an error when restoring and I'm not sure whether or not it is from the plugin side. I just post it here and I'm eager to look for your help if you have time on this. Thanks ahead.

**Environment**

- velero: 1.4.0
- velero-plugin-for-openstack: 0.2.0

**How to reproduce**

1. Create a backup via _velero backup create test_.
2. Delete pvc, pv manually to produce a so-called disaster.
3. Restore with the backup via _velero restore create restore-test --from-backup test_.

**Symptom**

Pv and pvc are restored successfully but there are errors in restore log. The restore status is "partially failed". 
```
time="2021-03-31T07:43:03Z" level=info msg="error restoring test-elb: Internal error occurred: failed to allocate requested HealthCheck NodePort 32034: provided port is already allocated" logSource="pkg/restore/restore.go:1152" restore=default/restore-3-31-1
time="2021-03-31T07:43:06Z" level=info msg="error restoring haproxy-nlb: Internal error occurred: failed to allocate requested HealthCheck NodePort 31568: provided port is already allocated" logSource="pkg/restore/restore.go:1152" restore=default/restore-3-31-1
time="2021-03-31T07:43:07Z" level=info msg="error restoring kong-proxy: Internal error occurred: failed to allocate requested HealthCheck NodePort 30983: provided port is already allocated" logSource="pkg/restore/restore.go:1152" restore=default/restore-3-31-1
```

**Questions**

- I'd like to ask the reason why the loadbalancer still need to be restored anyway? What I did is deleting the pv and pvc and what I expected is skipping the loadbalancer restoration just like any other irrelevant resources.
- The issue seems to be like velero is trying to create a new loadbalancer but it turns out to be impossible because the old one is still running and of course the port is already allocated. Could you please share more insights of this?

BTW, I put haproxy-nlb service yaml here for reference.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: '*.com'
    dns.gardener.cloud/ttl: "500"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"dns.gardener.cloud/class":"garden","dns.gardener.cloud/dnsnames":"*.com","dns.gardener.cloud/ttl":"500","service.beta.kubernetes.io/aws-load-balancer-type":"nlb"},"labels":{"run":"haproxy-ingress-nlb"},"name":"haproxy-nlb","namespace":"default"},"spec":{"externalTrafficPolicy":"Local","ports":[{"name":"https-external-lb","port":443,"protocol":"TCP","targetPort":443}],"selector":{"run":"haproxy-ingress-nlb"},"type":"LoadBalancer"}}
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  creationTimestamp: "2021-01-14T05:41:36Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  - garden.dns.gardener.cloud/service-dns
  labels:
    run: haproxy-ingress-nlb
  name: haproxy-nlb
  namespace: default
  resourceVersion: "33162"
  selfLink: /api/v1/namespaces/default/services/haproxy-nlb
  uid: a17094c4-0f32-4475-80a5-3d34a1cefa72
spec:
  clusterIP: *.*.*.*
  externalTrafficPolicy: Local
  healthCheckNodePort: 31568
  ports:
  - name: https-external-lb
    nodePort: 30210
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    run: haproxy-ingress-nlb
  sessionAffinity: None
  type: LoadBalancer
```

**Comment by Lirt** [comment]
Hi @AlwaySummit,

> The issue seems to be like velero is trying to create a new loadbalancer but it turns out to be impossible because the old one is still running and of course the port is already allocated. Could you please share more insights of this?

Yes that is true.

I think that only volume backup/restore is not supported in Velero yet (https://github.com/vmware-tanzu/velero/issues/504). So Velero tries to restore everything that was backuped. 

I would say that for such partial restore where you cannot reuse those unique ports, you can workaround in different manners:

1. Exclude LoadBalancers in restore (command not tested, but you get the idea here):

```bash
velero restore create \
                       restore-test \
                       --from-backup test \
                       --exclude-resources Service
```

2. Do volume (PV,PVC) backup only using selector (based on labels) `--selector`.

I cannot think of better solution now, but If you find it, please share it here.

**Comment by AlwaySummit** [comment]
Hi @Lirt 

Thanks for your sharing. Also, I found the code which is used for deciding whether velero should skip the restoration or not. I'm still a little bit confused why it doesnot pass the if condition because I didn't change anything at all. Any ideas?
```
if !equality.Semantic.DeepEqual(fromCluster, obj) {
			switch groupResource {
			case kuberesource.ServiceAccounts:
				desired, err := mergeServiceAccounts(fromCluster, obj)
				if err != nil {
					ctx.log.Infof("error merging secrets for ServiceAccount %s: %v", kube.NamespaceAndName(obj), err)
					warnings.Add(namespace, err)
					return warnings, errs
				}

				patchBytes, err := generatePatch(fromCluster, desired)
				if err != nil {
					ctx.log.Infof("error generating patch for ServiceAccount %s: %v", kube.NamespaceAndName(obj), err)
					warnings.Add(namespace, err)
					return warnings, errs
				}

				if patchBytes == nil {
					// In-cluster and desired state are the same, so move on to
					// the next item.
					return warnings, errs
				}

				_, err = resourceClient.Patch(name, patchBytes)
				if err != nil {
					warnings.Add(namespace, err)
				} else {
					ctx.log.Infof("ServiceAccount %s successfully updated", kube.NamespaceAndName(obj))
				}
			default:
				e := errors.Errorf("could not restore, %s. Warning: the in-cluster version is different than the backed-up version.", restoreErr)
				warnings.Add(namespace, e)
			}
			return warnings, errs
		}

		ctx.log.Infof("Restore of %s, %v skipped: it already exists in the cluster and is the same as the backed up version", obj.GroupVersionKind().Kind, name)
```

https://github.com/kubernetes/apimachinery/blob/master/pkg/api/equality/semantic.go
```
var Semantic = conversion.EqualitiesOrDie(
	func(a, b resource.Quantity) bool {
		// Ignore formatting, only care that numeric value stayed the same.
		// TODO: if we decide it's important, it should be safe to start comparing the format.
		//
		// Uninitialized quantities are equivalent to 0 quantities.
		return a.Cmp(b) == 0
	},
	func(a, b metav1.MicroTime) bool {
		return a.UTC() == b.UTC()
	},
	func(a, b metav1.Time) bool {
		return a.UTC() == b.UTC()
	},
	func(a, b labels.Selector) bool {
		return a.String() == b.String()
	},
	func(a, b fields.Selector) bool {
		return a.String() == b.String()
	},
)
```

**Comment by Lirt** [comment]
I'm not sure about the comparison and code snippet you mentioned.

Maybe the best would be to compare the service from the backup and the one in the cluster if they are really identical. If the services are identical and code decides to install it again it should be reported directly to Velero project as bug (if it's not intended by Velero to work like this).

**Comment by AlwaySummit** [comment]
Thanks. I'll reach out to velero team and if any progress, I'll let you know.
