### ISSUE TITLE
Apply openstack credentials for authentication

### ISSUE THREAD

**Issue by francestang1117** [Lirt/velero-plugin-for-openstack#25]
Hi @Lirt 
Currently I'm doing some development with openstack credentials and considering the environment, have you ever considering using application credentials to authenticate with keystone? Could you provide me with your suggestions or opinions? Thank you.

![Capture](https://user-images.githubusercontent.com/84653332/125746700-8fe93286-085c-488b-ad55-6353c54dbd53.PNG)

**Comment by Lirt** [comment]
Hi @francestang1117,

I never used it. 

As I'm looking into the code, authentication using application credentials was implemented in [gophercloud](https://github.com/gophercloud/gophercloud/pull/1224/files), but I'm not pushing those variables to [auth options](https://github.com/Lirt/velero-plugin-for-openstack/blob/master/src/utils/auth.go#L32). So with a small change it would be possible to use these environment variables to authenticate:
- `OS_APPLICATION_CREDENTIAL_ID`
- `OS_APPLICATION_CREDENTIAL_NAME`
- `OS_APPLICATION_CREDENTIAL_SECRET`

Just one question to properly understand you, do you want to authenticate from file, or using environment variables?

**Comment by francestang1117** [comment]
Hi @Lirt 
Thank you for your time on this issue. I prefer to authenticate from file as other cloud providers.

**Comment by Lirt** [comment]
Ok, but I will need to look into that, as there is no gophercloud auth function that will read from ENV file or INI file. 

So most likely I will need to parse INI file and load application_credential variables into correct ones in auth config.

**Comment by AlwaySummit** [comment]
Hi @Lirt 
Does the plugin support to read credentials from a file(/credentials/cloud) now?

**Comment by Lirt** [comment]
@AlwaySummit I never tried that. Potentially `clouds.yaml` could work (gophercloud specific default implementation).

But anyway I need to check all possibilities and update the code to take everything in mind.
1. Environment variables + Application credentials environment variables
2. Default paths for `cloud.yaml` (however only 1 cloud can work with it (1 velero instance can only work with 1 cloud) --> could be specifiable by env. var potentially)
3. Custom application credentials INI style file.

**Comment by AlwaySummit** [comment]
@Lirt got it. Thanks.

**Comment by AlwaySummit** [comment]
It seems I have to make adaptation for openstack with environment injection in my multiple cloud provider setup. But I'm still eager for the uniform implementation as other cloud in the future.:)
I truly understand there are enormous backlogs from your side and I'm always here waiting for the good news. Thanks.

**Comment by francestang1117** [comment]
Hi @Lirt
Do you plan to change the code to support the application credential authentication? If there are any problems, I think using the environment variables is also acceptable. Thank you.

**Comment by Lirt** [comment]
@francestang1117 Yes, I want to. I will try to find time for it this/next month.

**Comment by francestang1117** [comment]
Hi @Lirt 
May I ask the progress of adding the application credential? Thank you.

**Comment by AlwaySummit** [comment]
Hi @Lirt 

How's everything going recently? I'm wondering if there is any possibility that I could assist with the feature development because I'm totally aware of you're suffering from the overwork and overwhelming backlog.

**Comment by Lirt** [comment]
Hi guys I opened PR to address Application Credentials authentication and also authentication using files. 

Both things should be solved, but I need to run more tests tomorrow.

**Comment by Lirt** [comment]
Issue was resolved in #27 , please use new production image `v0.3.0`.
