### ISSUE TITLE
No `arm64` build available

### ISSUE THREAD

**Issue by clementnuss** [Lirt/velero-plugin-for-openstack#30]
Hi,

It's not possible to use this plugin on a raspberry pi 4 cluster, as it would require an arm64 build.
Can this be done (in the form of a custom tag for example: `:v.1.3.0-arm64` and published ?

Hope you can find some time for this small issue :)
Thanks for the plugin!
Clément

**Comment by clementnuss** [comment]
Ok a bit more investigation: while the go binaries were probably build correctly, now the issue is that the platform of the image still is amd64, not arm64 (you can see this on dockerhub)
two ways to solve this: append `--platform arm64` to the build process, or use `buildx` to build multi-arch images
will try to do a PR bor buildx later today

**Comment by Lirt** [comment]
Hi again,

sorry I was on vacation last days. I haven't done multiplatform docker builds yet, so it's new to me. I think I need to rewrite the Dockerfile a bit to make this happen. Also I'm not sure if using `alpine:3` will work and maybe I need to use `ARG` to allow setting final image to `arm64v8/alpine`.

**Comment by Lirt** [comment]
Hi again @clementnuss,

I built [multiplatform image and pushed it with temporary tag to dockerhub](https://hub.docker.com/layers/lirt/velero-plugin-for-openstack/v0.3.0-multiplatform/images/sha256-3a775699b85bd44b94201855ed2d0914375faa7672389e97f6a6f15f31e05168?context=repo). 

It's built from MR https://github.com/Lirt/velero-plugin-for-openstack/pull/33/files. 

I don't know how to test the image yet :-( so I need to rely on you. 

If you have a suggestion where I can try to run it (eg. in the cloud), please let me know.

**Comment by clementnuss** [comment]
Hi Ondrej,

No problem for testing, I'll run these images on my RPi. As for a solution to test them, I think AWS at some point introduced ARM-based cloud.

the image doesn't work yet though:
`velero-plugin-for-openstack standard_init_linux.go:228: exec user process caused: exec format error`
I'll try to understand why in your MR

**Comment by Lirt** [comment]
Hi again, 

Sorry for late answer.

Can it be possible, that you need different architecture 32/64 bit or something else different?

I think Dockerfile is correct in the MR. I will try to build AWS cluster with ARM to test it by myself, but I'm not sure what needs to be changed.

**Comment by clementnuss** [comment]
Hi,

here is the issue, I thought I had posted it, sorry for forgetting:

**Comment by Lirt** [comment]
Thank you very much!

I will rebuild tag `v0.3.1` as multiplatform image.

**Comment by Lirt** [comment]
Image [v0.3.1](https://hub.docker.com/layers/lirt/velero-plugin-for-openstack/v0.3.1/images/sha256-361fc139f18c24b1b4dc025475e748ae4463d80a594c01627843829668820e35?context=explore) uploaded.

Thank you again.
