### ISSUE TITLE
Question about object lifecycle

### ISSUE THREAD

**Issue by AlwaySummit** [Lirt/velero-plugin-for-openstack#55]
Hi @Lirt,

I'd like to ask a question about object lifecycle of swift. Since swift supports Expiring Object(https://docs.openstack.org/swift/latest/overview_expiring_objects.html), is there any ways to set a time limitation of backup object?

**Comment by Lirt** [comment]
Hi @AlwaySummit,

Velero supports configuration of backup TTL in their CRDs. So for this purpose you can use either `backup.spec.ttl` (for manually created backup) or `schedule.spec.template.ttl` (for scheduled backups). 

I think this functionality is enough for all use cases. If not, please let me know.

**Comment by AlwaySummit** [comment]
Thanks @Lirt. That would be helpful.
