### ISSUE TITLE
[FEAT] "clone" as a "snapshot"

### ISSUE THREAD

**Issue by kayrus** [Lirt/velero-plugin-for-openstack#78]
**Is your feature request related to a problem? Please describe.**

Both Cinder Volume and Manila Share snapshots make unavailable the source resource to be deleted. Causing PV/PVC k8s resources to stuck on deletion.

**Describe the solution you'd like**

I propose an option (or a different plugin key, e.g. a new snapshot driver name with the `-clone` suffix at the end) which will make a full Volume/Share clone. This will allow not to lock the source share from being deleted.

**Comment by Lirt** [comment]
Hi,

Yes cloning the volume sounds like a viable strategy. It would be great if we could potentially support both strategies as both have some ups and downs (but I didn't do research about it yet, it's only an idea). 

One thing is a bit unclear to me and it's how would it go along with the plugin interface. There is a function to _create snapshot_ (backup) and then _create volume from snapshot_ (restore). So the implementation with clone would probably skip functionality of _create volume from snapshot_ part but there could be some hidden consequences during restoration process (:shrug:).

Also I wouldn't mix this feature together with Manila MR. Or if you want to implement it for Manila then it should not affect Cinder plugin in the same MR.
